### ISSUE TITLE
SSHing into an instance with the wrong username results in a SSHException

### ISSUE THREAD

**Issue by ktdrv** [nchammas/flintrock#207] opened 2017-07-28 23:37 UTC
Launching a new cluster with the wrong username set by the `--ec2-user` option fails with a seemingly-unrelated `paramiko.ssh_exception.SSHException: not a valid EC private key file` error.

This because key handling in Paramiko is terribad (not my words): paramiko/paramiko#387.

We can probably safely catch this particular error and raise a more informative one because EC2 key-based auth doesn't even work with ECDSA keys.

Steps to replicate: `flintrock launch --ec2-ami=<Amazon Linux AMI ID> --ec2-user=theboss cluster-mcclusterface`
* Flintrock version: 0.8, also 0.9dev
* Python version: 3.6.1
* OS: MacOS Sierra

**Comment by nchammas** [comment] 2017-07-29 18:09
Duplicate of #130 and #171.

I'll submit a PR for this and ask you to test it, @ktdrv, if you don't mind. I get a different error than you when I put in the wrong username (protocol banner error), but perhaps I can find a solution that gives the correct hint for both of us.

**Closed** 2017-08-01 17:23 UTC
